default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: about-development

test:
  <<: *default
  database: about-test

production:
  <<: *default
  host: <%= ENV["DB_HOST"] %>
  database: about-production
  username: about
  password: <%= ENV["POSTGRES_PASSWORD"] %>
