default: &default
  host: localhost
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database: about-development
  username: carsoncole
  password: password

test:
  <<: *default
  database: about-test
  username: carsoncole
  password: password

production:
  <<: *default
  database: carsonrcole-production
  username: <%= Rails.application.credentials.postgresql.production.username %>
  password: <%= Rails.application.credentials.postgresql.production.password %>
