
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/about-development.sqlite3

test:
  <<: *default
  database: storage/about-test.sqlite3

production:
  <<: *default
  database: storage/about-production.sqlite3
