default: &default
  adapter: mysql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: PASSWORD
  host: localhost

development:
  <<: *default
  database: about_development

test:
  <<: *default
  database: about_test

production:
  <<: *default
  host: ENV["DB_HOST"]
  database: about_production
  password: ENV["MYSQL_ROOT_PASSWORD"]
