service: about
image: carsoncole/about

servers:
  web:
    - 147.182.252.0

registry:
  username: carsoncole
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    DB_HOST: 147.182.252.0
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD

accessories:
  db:
    image: postgres:15
    host: 147.182.252.0
    port: 5432
    env:
      clear:
        POSTGRES_USER: 'about'
        POSTGRES_DB: 'about_production'
      secret:
        - POSTGRES_PASSWORD
    directories:
      - data:/var/lib/postgresql/data
